### ISSUE TITLE
Freezing Talia import manager by clicking X instatly after click add on package

### ISSUE THREAD

**Issue by Maciej92Zareba** [ExtendRealityLtd/VRTK.Tilia.Package.Importer#7]
### Environment

* Code source: Talia package manager Version 1.1
* Code version: Talia package manager Version 1.1
* Platform version: Unity 2021.2.10
* 3rd party dependencies: None

### Steps to reproduce

clicking X instatly after click add on package

### Expected behavior

Stoping dowload, not hanging itself and doing nothing

### Current behavior

It is not importing talia and keep telling it is in progress

**Comment by Maciej92Zareba** [comment]
![obraz](https://user-images.githubusercontent.com/46682105/157905155-464c2748-253f-4b37-8a4c-ece1cd5c17ef.png)

**Comment by thestonefox** [comment]
PR with fix:

https://github.com/ExtendRealityLtd/VRTK.Tilia.Package.Importer/pull/8

Cannot prevent Unity from installing the selected packages as that is handled completely outside of the importer window and delegated to unity.

This fix just stops the crashing.
